# action.yml
env: # Or as an environment variable
  api_secret: ${{ secrets.TEST_KEY_API }}
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'